server:
  port: 8761
spring:
  application:
    name: eureka
  security:
    user:
      name: javaboy
      password: 123
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://javaboy:123@localhost:${server.port}/eureka/