spring:
  datasource:
    dynamic:
      primary: master #设置默认的数据源或者数据源组,默认值即为master
      strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
      datasource:
        master:
          url: jdbc:mysql://localhost:3306/test08?serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123
        slave_1:
          url: jdbc:mysql://localhost:3306/test09?serverTimezone=Asia/Shanghai&useSSL=false
          username: root
          password: 123